177 [PDP Popup] Why should I try this instead
aemsites/danaher-optimus pull request #212
Opened 2024-08-09 13:53 UTC by VSriPalivela

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #211

Test URLs:
- Before: https://main--danaher-optimus--aemsites.hlx.page/en-us/products/primary-antibodies/ki67-antibody-ab15580
- After: https://177-pdp-popup-why-should-i-try-this--danaher-optimus--aemsites.hlx.page/en-us/products/primary-antibodies/ki67-antibody-ab15580

2024-08-12 09:15 UTC, sharanagoudapatil requested changes
Hi @VSriPalivela 
- Please remove this block - popup-alternative.js, as this is the default content, and we don't require separate block.
- Remove these popup-alternative.js & popup-alternative.css files
- Remove an entry from build-css.js also.

2024-08-12 15:38 UTC, VSriPalivela commented
> Hi @VSriPalivela
> 
> * Please remove this block - popup-alternative.js, as this is the default content, and we don't require separate block.
> * Remove these popup-alternative.js & popup-alternative.css files
> * Remove an entry from build-css.js also.
> 
> cc: @rgravitvl

Hi @sharanagoudapatil 
Incorporated the review comments please review

2024-08-13 04:41 UTC, sharanagoudapatil approved these changes

2024-08-13 08:37 UTC, rgravitvl approved these changes

2024-08-13 08:40 UTC, VSriPalivela commented
PR Approved please merge it to main branch.

2024-08-14 05:13 UTC, merged